# Generated by Django 2.0.5 on 2018-05-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Cars',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
