# Generated by Django 2.0.5 on 2018-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180526_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
